### PR TITLE
add nvmrc for easier, more stable development

### PR DESCRIPTION
**Pull request by circAssimilate**
When first setting up the repo I had some troubles with `yarn start:examples` and `yarn build:watch` not working. After trying a few different types of node I found the latest stable version (`v12.13.1`) on https://nodejs.org/en/ worked well. This PR will add an `.nvmrc` file for those who use Node Version Manager to make development across several projects more reliable and less frustrating. Totally open to another node version if the one for @praneshr's env is different that `v12.13.1`.

### CODE REVIEW

**Comment by praneshr** [comment]
@circAssimilate This is very useful. But, I don't think everyone uses `nvm`. Even I use [`n`](https://www.npmjs.com/package/n) for managing my node versions. Can we go with a generic approach to address this? Can we try [engines](https://docs.npmjs.com/files/package.json#engines) in package.json? If you can address this quickly, I can include this change with v3.0 :)

Thanks again for your contributions.

**Comment by circAssimilate** [comment]
No probo, @praneshr. Unfortunately, after doing a bit of looking I couldn't find a clear way to actually make use of package.json's `engine` key. Have you come across any standard way? Totally up to you of course but I feel it's ok to be prescriptive with a node version manager (I'm ok with `nvm` or `n`) as long as it's standard - at least until NPM makes it as easy (or I learn a way they've already provided). Happy to make the PR if you can point me in the right direction solely using NPM!

**Comment by circAssimilate** [comment]
No probo, @praneshr. Unfortunately, after doing a bit of looking I couldn't find a clear way to actually make use of package.json's `engine` key. Have you come across any standard way? Totally up to you of course but I feel it's ok to be prescriptive with a node version manager (I'm ok with `nvm` or `n`) as long as it's standard - at least until NPM makes it as easy (or I learn a way they've already provided). Happy to make the PR if you can point me in the right direction solely using NPM!

**Comment by praneshr** [comment]
Hi @circAssimilate, thanks for the reply. However, I've fixed it myself by adding `engines`.

Check https://github.com/praneshr/react-diff-viewer/pull/58/

**Comment by circAssimilate** [comment]
Thanks, @praneshr! It may be helpful to add a recommended approach to using that engine spec via the command line - but glad it's at least there for manual reference.

**Pull request closed without merging**
